[package]
name = "rs3cache"
version = "0.1.0"
authors = ["mejrs"]
edition = "2018"

[profile.release]
lto = "thin"

[lib]
name = "rs3cache"
# dual types make it work both for compiling as package and python lib
crate-type = ["lib", "cdylib"]

[dependencies]
sqlite = "0.26.0"
libflate = "1.0.4"
bytes = "1.0.1"
itertools = "0.10.0"
ndarray = "0.15.1"
image = "0.23.14"
regex = "1.4.5"
futures = "0.3.14"
async-std = "1.9.0"
num_cpus = "1.13.0"
serde_json = "1.0.64"
serde = { version = "1.0.125", features = ["derive"] }
serde_with = "1.8.0"
bzip2 = "0.4.2"
static_assertions = "1.1.0"
chrono = "0.4.19"
path-absolutize = "3.0.7"
pyo3 = { version = "0.14.1", optional = true}
clap = {version = "2.33.3", features = ["yaml"]}
indicatif = "0.16.2"

[dev-dependencies]
criterion = "0.3.4"

[features]
default = ["rs3"]
mockdata = []
save_mockdata = []
dont_save = []
fast = []
rs3 = []
osrs = []
