[package]
name = "rs3cache"
version = "0.1.0"
authors = ["mejrs"]
edition = "2021"
default-run = "rs3cache"

[workspace]
members = ["rs3cache_core", "rs3cache_macros", "rs3cache_utils", "rs3_py", "osrs_py"]

[profile.release]
lto = "thin"

[lib]
name = "rs3cache"
# dual types make it work both for compiling as package and python lib
crate-type = ["lib", "cdylib"]

[[bin]]
name = "rs3cache"
path = "src/main.rs"
required-features = ["rs3"]

[[bin]]
name = "osrscache"
path = "src/main.rs"
required-features = ["osrs"]


[dependencies]
rs3cache_macros = { path = "rs3cache_macros", version = "0.1.0", optional = true  }
rs3cache_core = { path = "rs3cache_core", version = "0.1.0" }
rs3cache_utils = { path = "rs3cache_utils", version = "0.1.0" }
itertools = "0.10.1"
ndarray = "0.15.3"
image = "0.23.14"
regex = "1.5.4"
futures = "0.3.17"
async-std = "1.10.0"
serde_json = "1.0.67"
serde = { version = "1.0.130", features = ["derive"] }
serde_with = "1.10.0"
pyo3 = { version = "0.14.5", features = ["extension-module"], optional = true }
structopt = "0.3.23"
indicatif = "0.16.2"
path_macro = "1.0.0"
fstrings = "0.2.3"
filetime = { version = "0.2.15", optional = true }
rayon = "1.5.1"

[features]
python = ["pyo3", "rs3cache_core/python", "rs3cache_macros"]
mockdata = ["rs3cache_core/mockdata"]
save_mockdata = ["rs3cache_core/save_mockdata"]
fast = []
rs3 = ["rs3cache_core/rs3", "filetime"]
osrs = ["rs3cache_core/osrs"]
377 = []

