[package]
name = "osrs"
version = "0.1.0"
edition = "2021"

[lib]
name = "osrs"
crate-type = ["lib", "cdylib"]

[dependencies]
rs3cache = { path = "..", version = "0.1.0", features=["osrs", "pyo3"] }
pyo3 = { version = "0.17.3", features = ["extension-module"]}
