name: Python bindings

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6' # minimum supported version
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true
    - name: Python
      run: |
        pip install setuptools
        pip install wheel
        pip install setuptools-rust
        python setup.py develop
      # use install instead of develop for actually building in release mode
