[package]
name = "rs3"
version = "0.1.0"
edition = "2021"

[lib]
name = "rs3"
crate-type = ["cdylib"]

[dependencies]
rs3cache = { path = "..", version = "0.1.0", features=["rs3", "pyo3"] }
pyo3 = { version = "0.15", features = ["extension-module"]}
